name: CI-CD-Piplene-to-AWS-Elastibeanstalk
env:
  EB_PACKAGE_S3_BUCKET : "oper25-project-github-actions-application-packeges"
  EB_APPLICATION_NAME : "Myflask"
  EB_ENVORONMENT_NAME : "Myflask-env"
  DEPLOY_PACKAGE_NAME : "flask_app+${{github.sha}}.zip"
  AWS_REGION_NAME : "us-east-1"

on:
  push:
    branches: [ main ]


jobs:
  my_ci_part:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment packege
      run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
      
      
